version: '3.3'

services:
  base_datos:
    image: mysql:5.7
    #command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'p0l1t3cn1c0'
      MYSQL_DATABASE: 'integracion_continua'      
    ports:
      - 3306:3306
    volumes:
      - ./data_db:/var/lib/mysql
    networks: 
      - netchat    
  cliente:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: 'base_datos'
    restart: always
    ports:
      - 8083:8080
    networks: 
      - netchat 
  chatjs:
    build: 
      context: ./node_project
    command: npm start
    restart: unless-stopped
    container_name: nuestro-server
    ports: 
      - 3000:3000
    volumes: 
      - ./node_project:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - netchat
networks: 
  netchat:

                
